openapi: 3.0.3
info:
  title: PostCrafter - AI Content Publisher
  description: Publish AI-generated, SEO-optimized articles directly from ChatGPT to WordPress with comprehensive media uploads, Yoast SEO integration, and category management.
  version: 1.0.0
  contact:
    name: PostCrafter Support
    email: support@postcrafter.com

servers:
  - url: https://postcrafter-api.vercel.app
    description: Production server

paths:
  /api/publish:
    post:
      summary: Publish AI-generated content to WordPress
      description: Create and publish SEO-optimized WordPress posts with media uploads, Yoast SEO fields, and category management. Perfect for AI-generated content with automatic SEO optimization.
      operationId: publishPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, content]
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 200
                  description: Post title (required)
                  example: Complete Guide to AI Content Creation
                content:
                  type: string
                  minLength: 1
                  maxLength: 50000
                  description: Post content in HTML format (required)
                  example: "<h2>Introduction</h2><p>AI content creation is revolutionizing how we produce digital content...</p>"
                excerpt:
                  type: string
                  maxLength: 500
                  description: Post excerpt/summary for SEO
                  example: Learn how to create AI-generated content with SEO optimization and WordPress publishing.
                status:
                  type: string
                  enum: [draft, publish, private]
                  default: draft
                  description: Post status (draft, publish, or private)
                categories:
                  type: array
                  items:
                    type: string
                  description: Category names (will be created if they don't exist)
                  example: [Technology, AI, Content Creation]
                tags:
                  type: array
                  items:
                    type: string
                  description: Tag names (will be created if they don't exist)
                  example: [ai-content, seo, wordpress]
                images:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                        format: uri
                        description: Image URL to download and upload
                      base64:
                        type: string
                        description: Base64 encoded image data (alternative to URL)
                      alt_text:
                        type: string
                        maxLength: 500
                        description: Alt text for accessibility and SEO
                      title:
                        type: string
                        maxLength: 200
                        description: Image title
                      caption:
                        type: string
                        maxLength: 1000
                        description: Image caption
                      featured:
                        type: boolean
                        default: false
                        description: Whether this image should be the featured image
                    oneOf:
                      - required: [url]
                      - required: [base64]
                  description: Images to upload and attach to the post
                yoast:
                  type: object
                  properties:
                    meta_title:
                      type: string
                      maxLength: 60
                      description: SEO meta title (recommended: 50-60 characters)
                    meta_description:
                      type: string
                      maxLength: 160
                      description: SEO meta description (recommended: 150-160 characters)
                    focus_keyword:
                      type: string
                      maxLength: 100
                      description: Primary focus keyword for SEO
                    keywords:
                      type: array
                      items:
                        type: string
                      description: Additional keywords for SEO
                    og_title:
                      type: string
                      maxLength: 60
                      description: Open Graph title for social media
                    og_description:
                      type: string
                      maxLength: 160
                      description: Open Graph description for social media
                    og_image:
                      type: string
                      format: uri
                      description: Open Graph image URL for social media
                    twitter_title:
                      type: string
                      maxLength: 60
                      description: Twitter Card title
                    twitter_description:
                      type: string
                      maxLength: 160
                      description: Twitter Card description
                    twitter_image:
                      type: string
                      format: uri
                      description: Twitter Card image URL
                  description: Yoast SEO meta fields for comprehensive SEO optimization
            examples:
              basic_post:
                summary: Basic post with title and content
                value:
                  title: Getting Started with PostCrafter
                  content: "<h2>Introduction</h2><p>PostCrafter is an AI-powered tool that helps you create and publish SEO-optimized content directly to WordPress...</p>"
                  status: publish
                  excerpt: Learn how to use PostCrafter to create and publish AI-generated content with SEO optimization.
              full_post:
                summary: Complete post with all features
                value:
                  title: Complete Guide to AI Content Creation
                  content: "<h2>Introduction</h2><p>AI content creation is revolutionizing how we produce digital content...</p>"
                  status: publish
                  excerpt: A comprehensive guide to using AI for content creation with SEO best practices.
                  categories: [Technology, AI]
                  tags: [content-creation, seo, wordpress]
                  images:
                    - url: https://example.com/featured-image.jpg
                      alt_text: AI Content Creation Process
                      featured: true
                  yoast:
                    meta_title: Complete Guide to AI Content Creation | PostCrafter
                    meta_description: Learn how to create AI-generated content with SEO optimization. Discover best practices for content creation and WordPress publishing.
                    focus_keyword: AI content creation
      responses:
        '200':
          description: Post published successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Whether the operation was successful
                  post:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: WordPress post ID
                      url:
                        type: string
                        format: uri
                        description: Published post URL
                      title:
                        type: string
                        description: Post title
                      status:
                        type: string
                        description: Post status
                      date:
                        type: string
                        format: date-time
                        description: Publication date
                      categories:
                        type: array
                        items:
                          type: string
                        description: Applied categories
                      tags:
                        type: array
                        items:
                          type: string
                        description: Applied tags
                  media:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: WordPress media ID
                        url:
                          type: string
                          format: uri
                          description: Media URL
                        alt_text:
                          type: string
                          description: Alt text
                        title:
                          type: string
                          description: Media title
                        caption:
                          type: string
                          description: Media caption
                        featured:
                          type: boolean
                          description: Whether this is the featured image
                    description: Uploaded media information
                  yoast:
                    type: object
                    description: Applied Yoast SEO data
                  warnings:
                    type: array
                    items:
                      type: string
                    description: Any warnings during processing
              examples:
                success:
                  summary: Successful post publication
                  value:
                    success: true
                    post:
                      id: 123
                      url: https://example.com/2024/01/getting-started-with-postcrafter/
                      title: Getting Started with PostCrafter
                      status: publish
                      date: '2024-01-15T10:30:00Z'
                      categories: [Technology, AI]
                      tags: [content-creation, seo]
                    media:
                      - id: 456
                        url: https://example.com/wp-content/uploads/2024/01/featured-image.jpg
                        alt_text: AI Content Creation
                        featured: true
                    yoast:
                      meta_title: Getting Started with PostCrafter | PostCrafter
                      meta_description: Learn how to use PostCrafter to create and publish AI-generated content with SEO optimization.
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        description: Error code
                      message:
                        type: string
                        description: Human-readable error message
                      details:
                        type: string
                        description: Detailed error information
                  statusCode:
                    type: integer
                    description: HTTP status code
        '401':
          description: Unauthorized - invalid API key
        '429':
          description: Too many requests - rate limit exceeded
        '500':
          description: Internal server error

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication. Include this header with all requests.

security:
  - ApiKeyAuth: []